package com.cg.emjdbc.model;

public enum EventManagementAppMenu {
	ADD,REMOVE,LIST,LISTOFASCENDINGORDEROFDATESHEDULED,LISTOFALPHABETICALORDEROFLOCATION,LISTOFPARTICULARLOCATION,LISTOFPARTICULARDATESHEDULED,QUIT;

}
